# Generated by Django 5.1.4 on 2025-05-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image_url', models.ImageField(upload_to='images/ads/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('electronics', 'Электроника'), ('clothing', 'Одежда'), ('books', 'Книги'), ('other', 'Другое')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('used', 'Б/у')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
