# Generated by Django 5.1.4 on 2025-05-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/ads/%Y/%m/%d/'),
        ),
    ]
